services:
  worker:
    image: dairoot/chatgpt-mirror:v0.0.7

    volumes:
      - chatgpt_data:/app/worker/.wrangler

    env_file:
      - .env

    ports:
      - "50001:50001"

    restart: always

volumes:
  chatgpt_data:
